[package]
name = "cthulhu-roller"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.68"
poise = "0.6.1"
rand = "0.8.5"
regex = "1.10.5"
shuttle-runtime = "0.46.0"
shuttle-serenity = "0.46.0"
tokio = "1.26.0"
tracing = "0.1.37"
