#!/usr/bin/env bash
set -Eeuo pipefail

cd "$(git -C "$(dirname "$(readlink -f "$0")")" rev-parse --show-toplevel)"

scripts/cargo-sort
scripts/format
scripts/check
scripts/check --all-features
scripts/clippy
scripts/clippy --all-features
scripts/udeps
scripts/udeps --all-features
